### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by timothymiller** [nextauthjs/next-auth-typescript-example#1]
I noticed this repo was created about the same time I started integrating nextauth.js into my TypeScript stack.

I wrote some TypeScript code for sending emails over SMTP + DKIM signing that integrates nicely with NextAuth.js in my project. Would this be of help to you whomever is maintaining this repo?

Best,
Tim

**Comment by Manubi** [comment]
I would love to see this :D

**Comment by balazsorban44** [comment]
we are currently not  doing anything actively with TS, so we wouldn't like to maintain another example like this one. migrating to TS might be a thing we do in the future, but until we feel confident about it, I wouldn't add an example.
