### ISSUE TITLE
Custom Models with typescript

### ISSUE THREAD

**Issue by lukvermeulen** [nextauthjs/next-auth-typescript-example#4]
Hey folks! I am looking for a working implementation of custom models with typescript. Thus far, I only found deprecated hacky ways of muting typescript, but not using it. 

E.g. in ```models/User.ts```, what type would I use for the ...```class User extends Adapters.TypeOrm.Models.User.model```?
Right now it says: ```Property 'Models' does not exist on type '{ Adapter: Adapter<ConnectionOptions, Record<string, unknown>, User, Profile, Session>; }'.ts(2339)``` 

Another example where I am stuck:
https://next-auth.js.org/tutorials/typeorm-custom-models The example here to implement the defined custom Model in ```[...nextauth].ts``` explains to pass an URI string to adapter: ```Adapters.TypeORM.Adapter``` (line 13). Typescript then tells me ```Argument of type 'string' is not assignable to parameter of type 'ConnectionOptions'.ts(2345)```

If anyone could point me into the right direction or a working example, that would be much appreciated!

**Comment by balazsorban44** [comment]
Hi there! We are currently trying to clean up the adapters TS types:

https://github.com/nextauthjs/next-auth/blob/main/types/adapters.d.ts

It recently changed. I will try to get back to you with more info, but the above source code could hopefully get you started. In the meantime, could you provide a code snippet/repo I could experiment on? The new `Adapter` interface hopefully could be used to backport to the old TS from DefinitelyTyped (which sorely needed to be simplified, but you can still find it here: https://github.com/nextauthjs/next-auth/pull/1870/files)

**Comment by lukvermeulen** [comment]
Hi, thanks for the quick reply and the valuable resources! Happy to hear there is current progress in this field. I will check them out and see how far I get ASAP. 

Meanwhile I'll send you an invite to a stripped repo that has basic functionality. 
Thanks!

**Comment by balazsorban44** [comment]
Just wanted to mention I did a small tweaking that may be relevant: https://github.com/nextauthjs/next-auth/pull/1887/files

**Comment by lukvermeulen** [comment]
Just wondering, if with the new Typescript way the here (https://next-auth.js.org/getting-started/typescript) described module augmentation is the correct way to extend custom models, e.g using roles and defining own adapters, or if the other way with extending the class is still the way to go? 

Previously I have done it like this (I think its the same as in the docs):
models/Users.ts
```
import Adapters from "_next-auth/adapters_";

// Extend the built-in models using class inheritance
export default class User extends Adapters.TypeORM.Models.User.model {
  constructor(name, email, image, emailVerified, roles) {
    super(name, email, image, emailVerified);
    if (roles) {
      this.roles = roles;
    }
  }
}

export const UserSchema = {
  name: "User",
  target: User,
  columns: {
    ...Adapters.TypeORM.Models.User.schema.columns,
    roles: {
      type: "string[]",
      nullable: true,
    },
  },
};
```
and the "_models/index.ts_": 
```
import User, { UserSchema } from "./User";

export default {
  User: {
    model: User,
    schema: UserSchema,
  },
};
```

It now looks like everything would happen in _types/next-auth.d.ts_, is that correct or am I heavily mistaken 😄

**Comment by balazsorban44** [comment]
we are still figuring out some of the things with the adapters TS, I'm also new to adapters in general, but I'll report back to you when we have something more stable. otherwise any help is welcome in the main repo! 😊

**Comment by balazsorban44** [comment]
Have done a whole lot of work on this in https://github.com/nextauthjs/next-auth/pull/1952 and https://github.com/nextauthjs/adapters/pull/77

Hopefully both posted issues from the original comment are fixed in `3.21.1`

**Comment by lukvermeulen** [comment]
Thanks for the hard work! Issues from original comment are both fixed. 
Only complaint by typescript is that all parameters seem to have implicitly have "any" type. Maybe this is due to my implementation, is there a new best way to extend the models / and adapters?

**Comment by balazsorban44** [comment]
If you are creating a custom adapter, you can use the `Adapter` interface. Check the implementation to give you an idea of how to expand it https://www.github.com/nextauthjs/next-auth/tree/main/types%2Fadapters.d.ts
