### ISSUE TITLE
Example for JWTOptions.encode?

### ISSUE THREAD

**Issue by jiveyTO** [nextauthjs/next-auth-typescript-example#5]
I'm trying to figure out why my encode function is not working for typescript here.
Anyone have any idea? Or can I get an example for the JWT option using custom encode/decode functions.

![image](https://user-images.githubusercontent.com/20135683/120877949-3e374b00-c587-11eb-8584-28b2bc8fd8e5.png)

So far I have something like this, but don't know if it's the right way to do it.

```
jwt: {
    secret: process.env.SECRET,
    encode: async (params) => {
      const { token, secret } = params as JWTEncodeParams
      return sign(token as JWT, secret as string, { algorithm: 'HS512' })
    },
    decode: async (params): Promise<JWT> => {
      const { token, secret } = params as JWTDecodeParams
      const decodedToken = verify(token as string, secret, { algorithms: ['HS512'] })
      return decodedToken as JWT
    }
  },
```

**Comment by lluia** [comment]
@jiveyTO just seeing this, for **Typescript** related question, the best is to open an issue on the main repo using the [relevant issue template](https://github.com/nextauthjs/next-auth/issues/new?assignees=lluia%2Cbalazsorban44&labels=question%2CTypeScript&template=typescript.md). 

There's no guarantee that your `encode` function is going to be called with the relevant params, hence you need to a bit more defensive in your checks:
```js
encode: async (params) => {
  const { token, secret } = params || {}
  if (token && secret) return sign(/*...*/)
}
```
